languageCode = "en"
languageName = "English"
weight = 1
title = "NeuronBit"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "The low level side of machine learning."

[author]
  name = "Dario Salvati"
  image = "img/avatar.png"
  headline = "Machine Learning Engineer making models go brrr."
  bio = "Machine Learning Engineer making models go brrr."
  links = [
    { linkedin = "https://linkedin.com/in/dwarez" },
    { github = "https://github.com/dwarez" },
  ]