languageCode = "en"
languageName = "English"
weight = 1
title = "The ML Surgeon"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/file.png"
  description = "The low level side of machine learning."

[params.author]
  name = "Dario Salvati"
  image = "/img/avatar.jpg"
  headline = "A surgeon for Machine Learning models."
  bio = "A surgeon for Machine Learning models."
  links = [
    { linkedin = "https://linkedin.com/in/dwarez" },
    { github = "https://github.com/dwarez" },
  ]
